Added failing test that shows habtm that references a scope that has a join fails.
Used to work in 3.0.  Fails in 3.1 because the join table is referenced
more than once.

3.0 sql:
SELECT "posts".* FROM "posts"
INNER JOIN "categories_posts" "categories_posts_join" ON "categories_posts_join"."post_id" = "posts"."id"
INNER JOIN "categories" ON "categories"."id" = "categories_posts_join"."category_id"
INNER JOIN "categories_posts" ON "posts".id = "categories_posts".post_id
WHERE ("categories_posts".category_id = 1 )

3.1 sql:
SELECT "posts".* FROM "posts"
INNER JOIN "categories_posts" ON "categories_posts"."post_id" = "posts"."id"
INNER JOIN "categories" ON "categories"."id" = "categories_posts"."category_id"
INNER JOIN "categories_posts" ON "posts"."id" = "categories_posts"."post_id"
WHERE "categories_posts"."category_id" = 1
PGError: ERROR:  table name "categories_posts" specified more than once