Revert "Fix for CVE-2013-0155"
This reverts commit 6284c345f7fe09a1050edb85d18fec14b9984fe3.

This one causes the app not to load with:
`method_missing': undefined local variable or method `top_level' for #<Class:0xcaf2d30> (NameError)

So I suspet that "top_level" simply isn't properly defined yet.