will now return nil instead of raise a NoMethodError if the receiving object does not implement the method
Conflicts:
	activesupport/CHANGELOG.md
	activesupport/lib/active_support/core_ext/object/try.rb
	activesupport/test/core_ext/object_and_class_ext_test.rb